# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('category', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], default='Single', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('smoking', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='room',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
    ]
