# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
